### PR TITLE
Fixes Permission denied exception for CSV

### PR DESCRIPTION
**Pull request by githengi**

### CODE REVIEW

**Review by rehammuzzamil — DISMISSED** [review]
Looks good to me. Also tested the flow with this deployed branch on stage-server.

**Comment by rehammuzzamil** [comment]
Removed core upgrade version @githengi  @bennsimon

**Comment by rehammuzzamil** [comment]
There is a minor issue with this approach, the zip file is downloaded successfully and it contains all 5 CSV files but using the `Extract here `option (of Ubuntu) extracts an empty file.
But opening it with the` archive manager > Extract > Extract` successfully extracts all the files in the destination folder.

I think we can merge this PR to unblock QA and later fix this in some other PR if needed. What do you think @githengi?
cc: @cafootitt

**Review by rehammuzzamil — APPROVED** [review]
https://github.com/OpenSRP/opensrp-server-web/pull/759#issuecomment-786451850 Please check.

**Comment by githengi** [comment]
> [#759 (comment)](https://github.com/OpenSRP/opensrp-server-web/pull/759#issuecomment-786451850) Please check.

I able to extract the zip and open the CSV and they look good to me

**Pull request merged**
